theme: jekyll-theme-minimal
title: Fotografia secondo Piero Rossi
description: La fotografia non è né pura arte né pura scienza, come tutte le cose bisogna saper bilanciare le 2 per ottenere risultati degni di nota
